# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Peter Sowah"

# A description of your site for social meta tag, search engines, and feed.xml
description: "My personal blog where I write about programming topics - PHP, Ruby, JavaScript and some DevOps & Databases. &#128526"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://petersowah.dev"

# Site navigation - each item must have a title and a url.
navigation:
- text: Blog
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/
#- text: Download
#  url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
disqus: peter_sowah

# Author information - author info at the bottom of the post
author_name: "Peter Sowah"
author_bio: "I am a Software Developer with a passion for providing solutions to problems using tech- mainly programming."
author_url:  "http://petersowah.dev"
author_location: "Accra, Ghana"
author_image: /assets/images/authorimage.png

# Social links in the site footer
twitter_username: "petersowah_"
#stackoverflow_username: ""
github_username: "petersowah"
#pinterest_username: "username"
instagram_username: "petersowah"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/page:num/'
plugins: [jekyll-paginate]

# Permalinks
permalink: /:title

markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
